### ISSUE TITLE
not able to do npm i

### ISSUE THREAD

**Issue by sudeepdk** [productdevbookcom/chatwoot#19]
![image](https://user-images.githubusercontent.com/3715273/235447022-31268d7e-f580-414b-88b0-8aeb4a48fd66.png)

**Comment by productdevbook** [comment]
soory docs

```
npm install @productdevbook/chatwoot

```

**Comment by productdevbook** [comment]
if used `pnpm` work pnpm add or pnpm install, but npm only install used.

**Comment by sudeepdk** [comment]
npm install @productdevbook/chatwoot => also not working same error coming

**Comment by productdevbook** [comment]
there is nothing i can do to it, you can reinstall nodejs and do a test

**Comment by productdevbook** [comment]
I'm closing this issue, because I don't have a situation
